site_name: python курс
# site_url: 
copyright: copyright &copy; 2022 ods.ai

repo_name: open-data-science/pycourse
repo_url: https://github.com/open-data-science/pycourse

theme:
  name: null

  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - главная: index.md
  - авторы: authors.md