site_name: python курс
# site_url: 
copyright: copyright &copy; 2022 ods.ai

repo_name: open-data-science/pycourse
repo_url: https://github.com/open-data-science/pycourse

theme:
  name: material

  static_templates:
    - 404.html

  font:
    text: Ubuntu
    code: JetBrains Mono

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - главная: index.md
  - авторы:
    - авторы: authors.md