site_name: python курс
# site_url: 
copyright: copyright &copy; 2022 ods.ai

repo_name: open-data-science/pycourse
repo_url: https://github.com/open-data-science/pycourse

theme:
  name: material

  static_templates:
    - 404.html

  font:
    text: Ubuntu
    code: JetBrains Mono

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - главная: index.md
  - авторы:
    - авторы: authors.md