name: cd-prod

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    
      - name: checkout code
        uses: actions/checkout@v3
    
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          # cache: 'pip'
    
      - name: install deps
        run: pip install mkdocs-material==8.4.2 mkdocs==1.3.0 mkdocs-material-extensions==1.0.3 markdown==3.2.1 pygments==2.12 pymdown-extensions==9.4
    
      - name: deploy mkdocs
        run: mkdocs gh-deploy --force
