name: cd-prod

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    
      - name: checkout code
        uses: actions/checkout@v3
    
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
    
      - name: install deps
        run: pip install mkdocs-material 
    
      - name: deploy mkdocs
        run: mkdocs gh-deploy --force
